In [1]:
import pandas as pd
import sqlite3
import os

In [2]:
conn = sqlite3.connect('nba.sqlite')
cursor = conn.cursor()
conn.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
output_folder = "csv"
os.makedirs(output_folder, exist_ok=True)

# # Print the table names
# for table in tables:
#     table_name = table[0]
#     # Read the table data into a pandas DataFrame
#     df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
#     output_file = os.path.join(output_folder, f"{table_name}.csv")
#     # Save DataFrame to CSV
#     df.to_csv(output_file, index=False)
# conn.close()

In [12]:
# # Read a CSV file into a DataFrame
# df1 = spark.read.csv("csv/game.csv", header=True, inferSchema=True)

# # Perform some PySpark operations
# # result = df1.groupBy("team_name_home").count()

# # Show the result
# df1.show()

In [3]:
# %%
from pyspark.sql import SparkSession
from pyspark.sql.functions import concat

# Create a SparkSession
spark = SparkSession.builder \
    .appName("PySpark Notebook") \
    .getOrCreate()

# %%

In [4]:
import os
# Specify the folder path
folder_path = "csv/"

# Get a list of all files in the folder
files = os.listdir(folder_path)

# Print the file names
for file in files:
    print(file)

common_player_info.csv
draft_combine_stats.csv
draft_history.csv
game.csv
game_info.csv
game_summary.csv
inactive_players.csv
line_score.csv
officials.csv
other_stats.csv
player.csv
play_by_play.csv
team.csv
team_details.csv
team_history.csv
team_info_common.csv

In [5]:
file_names = ["common_player_info.csv",
"draft_combine_stats.csv",
"draft_history.csv",
"game.csv",
"game_info.csv",
"game_summary.csv",
"inactive_players.csv",
"line_score.csv",
"officials.csv",
"other_stats.csv",
"player.csv",
"play_by_play.csv",
"team.csv",
"team_details.csv",
"team_history.csv",
"team_info_common.csv"]

In [14]:
dataframes = {}
for file_name in file_names:
    file_path = "csv/" + file_name  # Update with the actual folder path
    df = spark.read.csv(file_path, header=True, inferSchema=True)
    dataframes[file_name] = df

In [15]:
df_common_player_info = dataframes["common_player_info.csv"]
df_draft_combine_stats = dataframes["draft_combine_stats.csv"]
df_draft_history = dataframes["draft_history.csv"]
df_game= dataframes["game.csv"]
df_game_info = dataframes["game_info.csv"]
df_game_summary = dataframes["game_summary.csv"]
df_inactive_players = dataframes["inactive_players.csv"]
df_line_score = dataframes["line_score.csv"]
df_officials = dataframes["officials.csv"]
df_other_stats = dataframes["other_stats.csv"]
df_player = dataframes["player.csv"]
df_play_by_play = dataframes["play_by_play.csv"]
df_team = dataframes["team.csv"]
df_team_details = dataframes["team_details.csv"]
df_team_history = dataframes["team_history.csv"]
df_team_info_common = dataframes["team_info_common.csv"]

In [149]:
df_play_by_play.columns

['game_id',
 'eventnum',
 'eventmsgtype',
 'eventmsgactiontype',
 'period',
 'wctimestring',
 'pctimestring',
 'homedescription',
 'neutraldescription',
 'visitordescription',
 'score',
 'scoremargin',
 'person1type',
 'player1_id',
 'player1_name',
 'player1_team_id',
 'player1_team_city',
 'player1_team_nickname',
 'player1_team_abbreviation',
 'person2type',
 'player2_id',
 'player2_name',
 'player2_team_id',
 'player2_team_city',
 'player2_team_nickname',
 'player2_team_abbreviation',
 'person3type',
 'player3_id',
 'player3_name',
 'player3_team_id',
 'player3_team_city',
 'player3_team_nickname',
 'player3_team_abbreviation',
 'video_available_flag']

In [139]:
df_common_player_info.show()

+---------+----------+----------------+--------------------+------------------------+-------------------+--------------------+-------------------+---------------+-------+--------------------+------+------+----------+------+--------------+------------+--------------------------------+----------+-------------+-----------------+------------+------------+--------------------+---------+-------+------------+--------+-----------------+----------+-----------+------------+----------------+
|person_id|first_name|       last_name|  display_first_last|display_last_comma_first|    display_fi_last|         player_slug|          birthdate|         school|country|    last_affiliation|height|weight|season_exp|jersey|      position|rosterstatus|games_played_current_season_flag|   team_id|    team_name|team_abbreviation|   team_code|   team_city|          playercode|from_year|to_year|dleague_flag|nba_flag|games_played_flag|draft_year|draft_round|draft_number|greatest_75_flag|
+---------+----------+----------------+--------------------+------------------------+-------------------+--------------------+-------------------+---------------+-------+--------------------+------+------+----------+------+--------------+------------+--------------------------------+----------+-------------+-----------------+------------+------------+--------------------+---------+-------+------------+--------+-----------------+----------+-----------+------------+----------------+
|       51|   Mahmoud|      Abdul-Rauf|  Mahmoud Abdul-Rauf|     Abdul-Rauf, Mahmoud|      M. Abdul-Rauf|  mahmoud-abdul-rauf|1969-03-09 00:00:00|Louisiana State|    USA| Louisiana State/USA|   6-1|   162|       9.0|     1|         Guard|    Inactive|                               N|1610612743|      Nuggets|              DEN|     nuggets|      Denver|  mahmoud_abdul-rauf|   1990.0| 2000.0|           N|       Y|                Y|      1990|          1|           3|               N|
|     1505|     Tariq|     Abdul-Wahad|   Tariq Abdul-Wahad|      Abdul-Wahad, Tariq|     T. Abdul-Wahad|   tariq-abdul-wahad|1974-11-03 00:00:00| San Jose State| France|San Jose State/Fr...|   6-6|   235|       7.0|     9| Forward-Guard|    Inactive|                               N|1610612758|        Kings|              SAC|       kings|  Sacramento|   tariq_abdul-wahad|   1997.0| 2003.0|           N|       Y|                Y|      1997|          1|          11|               N|
|    76007|      John|       Abramovic|      John Abramovic|         Abramovic, John|       J. Abramovic|      john-abramovic|1919-02-09 00:00:00|          Salem|    USA|           Salem/USA|   6-3|   195|       2.0|  null|       Forward|    Inactive|                               N|1610610031|      Ironmen|              PIT|     ironmen|  Pittsburgh|HISTADD_brooms_ab...|   1946.0| 1947.0|           N|       Y|                Y| Undrafted|  Undrafted|   Undrafted|               N|
|   203112|    Quincy|             Acy|          Quincy Acy|             Acy, Quincy|             Q. Acy|          quincy-acy|1990-10-06 00:00:00|         Baylor|    USA|          Baylor/USA|   6-7|   240|       7.0|  null|       Forward|    Inactive|                               N|         0|         null|             null|        null|        null|          quincy_acy|   2012.0| 2018.0|           Y|       Y|                Y|      2012|          2|          37|               N|
|   200801|    Hassan|           Adams|        Hassan Adams|           Adams, Hassan|           H. Adams|        hassan-adams|1984-06-20 00:00:00|        Arizona|    USA|         Arizona/USA|   6-4|   220|       2.0|  null|       Forward|    Inactive|                               N|         0|         null|             null|        null|        null|        hassan_adams|   2006.0| 2008.0|           N|       Y|                Y|      2006|          2|          54|               N|
|   203919|    Jordan|           Adams|        Jordan Adams|           Adams, Jordan|           J. Adams|        jordan-adams|1994-07-08 00:00:00|           UCLA|    USA|            UCLA/USA|   6-5|   209|       3.0|     3|         Guard|    Inactive|                               N|1610612763|    Grizzlies|              MEM|   grizzlies|     Memphis|        jordan_adams|   2014.0| 2015.0|           Y|       Y|                Y|      2014|          1|          22|               N|
|      912|    Rafael|         Addison|      Rafael Addison|         Addison, Rafael|         R. Addison|      rafael-addison|1964-07-22 00:00:00|       Syracuse|    USA|        Syracuse/USA|   6-8|   241|       6.0|     7|       Forward|    Inactive|                               N|1610612751|         Nets|              NJN|        nets|  New Jersey|      rafael_addison|   1986.0| 1996.0|           N|       Y|                Y|      1986|          2|          39|               N|
|   201336|     Blake|          Ahearn|        Blake Ahearn|           Ahearn, Blake|          B. Ahearn|        blake-ahearn|1984-05-27 00:00:00| Missouri State|    USA|  Missouri State/USA|   6-2|   190|       4.0|     2|         Guard|    Inactive|                               N|1610612748|         Heat|              MIA|        heat|       Miami|        blake_ahearn|   2007.0| 2011.0|           Y|       Y|                Y| Undrafted|  Undrafted|   Undrafted|               N|
|   202374|   Solomon|           Alabi|       Solomon Alabi|          Alabi, Solomon|           S. Alabi|       solomon-alabi|1988-03-21 00:00:00|  Florida State|Nigeria|Florida State/Nig...|   7-1|   252|       3.0|    50|        Center|    Inactive|                               N|1610612761|      Raptors|              TOR|     raptors|     Toronto|       solomon_alabi|   2010.0| 2011.0|           Y|       Y|                Y|      2010|          2|          50|               N|
|    76019|      Mark|          Alarie|         Mark Alarie|            Alarie, Mark|          M. Alarie|         mark-alarie|1963-12-11 00:00:00|           Duke|    USA|            Duke/USA|   6-8|   217|       5.0|    31|       Forward|    Inactive|                               N|1610612764|      Bullets|              WAS|     wizards|  Washington| HISTADD_mark_alarie|   1986.0| 1990.0|           N|       Y|                Y|      1986|          1|          18|               N|
|   203128|    Furkan|         Aldemir|      Furkan Aldemir|         Aldemir, Furkan|         F. Aldemir|      furkan-aldemir|1991-08-09 00:00:00|    Galatasaray| Turkey|  Galatasaray/Turkey|  6-10|   240|       2.0|    19|Forward-Center|    Inactive|                               N|1610612755|        76ers|              PHI|      sixers|Philadelphia|      furkan_aldemir|   2014.0| 2014.0|           N|       Y|                Y|      2012|          2|          53|               N|
|   200746|  LaMarcus|        Aldridge|   LaMarcus Aldridge|      Aldridge, LaMarcus|        L. Aldridge|   lamarcus-aldridge|1985-07-19 00:00:00|   Texas-Austin|    USA|    Texas-Austin/USA|  6-11|   250|      17.0|    21|Center-Forward|    Inactive|                               N|1610612751|         Nets|              BKN|        nets|    Brooklyn|   lamarcus_aldridge|   2006.0| 2021.0|           N|       Y|                Y|      2006|          1|           2|               N|
|  1626146|     Cliff|       Alexander|     Cliff Alexander|        Alexander, Cliff|       C. Alexander|     cliff-alexander|1995-11-16 00:00:00|         Kansas|    USA|          Kansas/USA|   6-8|   240|       2.0|    34|       Forward|    Inactive|                               N|1610612757|Trail Blazers|              POR|     blazers|    Portland|     cliff_alexander|   2015.0| 2015.0|           Y|       Y|                Y| Undrafted|  Undrafted|   Undrafted|               N|
|    76022|      Gary|       Alexander|      Gary Alexander|         Alexander, Gary|       G. Alexander|      gary-alexander|1969-11-01 00:00:00|  South Florida|    USA|   South Florida/USA|   6-7|   240|       1.0|    16|       Forward|    Inactive|                               N|1610612739|    Cavaliers|              CLE|   cavaliers|   Cleveland|HISTADD_gary_alex...|   1993.0| 1993.0|           N|       Y|                Y| Undrafted|  Undrafted|   Undrafted|               N|
|  1629734|      Kyle|       Alexander|      Kyle Alexander|         Alexander, Kyle|       K. Alexander|      kyle-alexander|1996-10-21 00:00:00|      Tennessee| Canada|    Tennessee/Canada|  6-10|   216|       2.0|    17|Forward-Center|    Inactive|                               N|1610612748|         Heat|              MIA|        heat|       Miami|      kyle_alexander|   2019.0| 2019.0|           Y|       Y|                Y| Undrafted|  Undrafted|   Undrafted|               N|
|  1629638|   Nickeil|Alexander-Walker|Nickeil Alexander...|    Alexander-Walker,...|N. Alexander-Walker|nickeil-alexander...|1998-09-02 00:00:00|  Virginia Tech| Canada|Virginia Tech/Canada|   6-5|   205|       3.0|     9|         Guard|      Active|                               Y|1610612750| Timberwolves|              MIN|timberwolves|   Minnesota|nickeil_alexander...|   2019.0| 2022.0|           Y|       Y|                Y|      2019|          1|          17|               N|
|  1628960|   Grayson|           Allen|       Grayson Allen|          Allen, Grayson|           G. Allen|       grayson-allen|1995-10-08 00:00:00|           Duke|    USA|            Duke/USA|   6-4|   198|       4.0|    12|         Guard|      Active|                               Y|1610612749|        Bucks|              MIL|       bucks|   Milwaukee|       grayson_allen|   2018.0| 2022.0|           Y|       Y|                Y|      2018|          1|          21|               N|
|      706|    Jerome|           Allen|        Jerome Allen|           Allen, Jerome|           J. Allen|        jerome-allen|1973-01-28 00:00:00|   Pennsylvania|    USA|    Pennsylvania/USA|   6-4|   184|       2.0|    53|         Guard|    Inactive|                               N|1610612754|       Pacers|              IND|      pacers|     Indiana|        jerome_allen|   1995.0| 1996.0|           N|       Y|                Y|      1995|          2|          49|               N|
|     2124|     Malik|           Allen|         Malik Allen|            Allen, Malik|           M. Allen|         malik-allen|1978-06-27 00:00:00|      Villanova|    USA|       Villanova/USA|  6-10|   255|      11.0|    35|       Forward|    Inactive|                               N|1610612748|         Heat|              MIA|        heat|       Miami|         malik_allen|   2001.0| 2010.0|           N|       Y|                Y| Undrafted|  Undrafted|   Undrafted|               N|
|     1824|     Peter|           Aluma|         Peter Aluma|            Aluma, Peter|           P. Aluma|         peter-aluma|1973-04-26 00:00:00|        Liberty|    USA|         Liberty/USA|  6-10|   260|       1.0|  null|        Center|    Inactive|                               N|         0|         null|             null|        null|        null|         peter_aluma|   1998.0| 1998.0|           N|       Y|                Y| Undrafted|  Undrafted|   Undrafted|               N|
+---------+----------+----------------+--------------------+------------------------+-------------------+--------------------+-------------------+---------------+-------+--------------------+------+------+----------+------+--------------+------------+--------------------------------+----------+-------------+-----------------+------------+------------+--------------------+---------+-------+------------+--------+-----------------+----------+-----------+------------+----------------+
only showing top 20 rows

In [18]:
# for i, df in enumerate(dataframes):
#     print(f"DataFrame {i+1}: {file_names[i]}")
#     df.show()

In [136]:
df_draft_combine_stats.printSchema()

root
 |-- season: integer (nullable = true)
 |-- player_id: integer (nullable = true)
 |-- first_name: string (nullable = true)
 |-- last_name: string (nullable = true)
 |-- player_name: string (nullable = true)
 |-- position: string (nullable = true)
 |-- height_wo_shoes: double (nullable = true)
 |-- height_wo_shoes_ft_in: string (nullable = true)
 |-- height_w_shoes: double (nullable = true)
 |-- height_w_shoes_ft_in: string (nullable = true)
 |-- weight: double (nullable = true)
 |-- wingspan: double (nullable = true)
 |-- wingspan_ft_in: string (nullable = true)
 |-- standing_reach: double (nullable = true)
 |-- standing_reach_ft_in: string (nullable = true)
 |-- body_fat_pct: double (nullable = true)
 |-- hand_length: double (nullable = true)
 |-- hand_width: double (nullable = true)
 |-- standing_vertical_leap: double (nullable = true)
 |-- max_vertical_leap: double (nullable = true)
 |-- lane_agility_time: double (nullable = true)
 |-- modified_lane_agility_time: double (nullable = true)
 |-- three_quarter_sprint: double (nullable = true)
 |-- bench_press: double (nullable = true)
 |-- spot_fifteen_corner_left: string (nullable = true)
 |-- spot_fifteen_break_left: string (nullable = true)
 |-- spot_fifteen_top_key: string (nullable = true)
 |-- spot_fifteen_break_right: string (nullable = true)
 |-- spot_fifteen_corner_right: string (nullable = true)
 |-- spot_college_corner_left: string (nullable = true)
 |-- spot_college_break_left: string (nullable = true)
 |-- spot_college_top_key: string (nullable = true)
 |-- spot_college_break_right: string (nullable = true)
 |-- spot_college_corner_right: string (nullable = true)
 |-- spot_nba_corner_left: string (nullable = true)
 |-- spot_nba_break_left: string (nullable = true)
 |-- spot_nba_top_key: string (nullable = true)
 |-- spot_nba_break_right: string (nullable = true)
 |-- spot_nba_corner_right: string (nullable = true)
 |-- off_drib_fifteen_break_left: string (nullable = true)
 |-- off_drib_fifteen_top_key: string (nullable = true)
 |-- off_drib_fifteen_break_right: string (nullable = true)
 |-- off_drib_college_break_left: string (nullable = true)
 |-- off_drib_college_top_key: string (nullable = true)
 |-- off_drib_college_break_right: string (nullable = true)
 |-- on_move_fifteen: string (nullable = true)
 |-- on_move_college: string (nullable = true)

In [22]:
column_names = df_draft_combine_stats.columns
print(column_names)

['season', 'player_id', 'first_name', 'last_name', 'player_name', 'position', 'height_wo_shoes', 'height_wo_shoes_ft_in', 'height_w_shoes', 'height_w_shoes_ft_in', 'weight', 'wingspan', 'wingspan_ft_in', 'standing_reach', 'standing_reach_ft_in', 'body_fat_pct', 'hand_length', 'hand_width', 'standing_vertical_leap', 'max_vertical_leap', 'lane_agility_time', 'modified_lane_agility_time', 'three_quarter_sprint', 'bench_press', 'spot_fifteen_corner_left', 'spot_fifteen_break_left', 'spot_fifteen_top_key', 'spot_fifteen_break_right', 'spot_fifteen_corner_right', 'spot_college_corner_left', 'spot_college_break_left', 'spot_college_top_key', 'spot_college_break_right', 'spot_college_corner_right', 'spot_nba_corner_left', 'spot_nba_break_left', 'spot_nba_top_key', 'spot_nba_break_right', 'spot_nba_corner_right', 'off_drib_fifteen_break_left', 'off_drib_fifteen_top_key', 'off_drib_fifteen_break_right', 'off_drib_college_break_left', 'off_drib_college_top_key', 'off_drib_college_break_right', 'on_move_fifteen', 'on_move_college']

In [23]:
column_types = df_draft_combine_stats.dtypes
print(column_types)

[('season', 'int'), ('player_id', 'int'), ('first_name', 'string'), ('last_name', 'string'), ('player_name', 'string'), ('position', 'string'), ('height_wo_shoes', 'double'), ('height_wo_shoes_ft_in', 'string'), ('height_w_shoes', 'double'), ('height_w_shoes_ft_in', 'string'), ('weight', 'double'), ('wingspan', 'double'), ('wingspan_ft_in', 'string'), ('standing_reach', 'double'), ('standing_reach_ft_in', 'string'), ('body_fat_pct', 'double'), ('hand_length', 'double'), ('hand_width', 'double'), ('standing_vertical_leap', 'double'), ('max_vertical_leap', 'double'), ('lane_agility_time', 'double'), ('modified_lane_agility_time', 'double'), ('three_quarter_sprint', 'double'), ('bench_press', 'double'), ('spot_fifteen_corner_left', 'string'), ('spot_fifteen_break_left', 'string'), ('spot_fifteen_top_key', 'string'), ('spot_fifteen_break_right', 'string'), ('spot_fifteen_corner_right', 'string'), ('spot_college_corner_left', 'string'), ('spot_college_break_left', 'string'), ('spot_college_top_key', 'string'), ('spot_college_break_right', 'string'), ('spot_college_corner_right', 'string'), ('spot_nba_corner_left', 'string'), ('spot_nba_break_left', 'string'), ('spot_nba_top_key', 'string'), ('spot_nba_break_right', 'string'), ('spot_nba_corner_right', 'string'), ('off_drib_fifteen_break_left', 'string'), ('off_drib_fifteen_top_key', 'string'), ('off_drib_fifteen_break_right', 'string'), ('off_drib_college_break_left', 'string'), ('off_drib_college_top_key', 'string'), ('off_drib_college_break_right', 'string'), ('on_move_fifteen', 'string'), ('on_move_college', 'string')]

In [ ]:
df = spark.read.csv("csv/team.csv", header=True, inferSchema=True)

# Perform some PySpark operations
# result = df.groupBy("team_name_home").count()

# Show the result
column_names = df.columns
df.show()

+----------+--------------------+------------+------------+------------+-------------+------------+
|        id|           full_name|abbreviation|    nickname|        city|        state|year_founded|
+----------+--------------------+------------+------------+------------+-------------+------------+
|1610612737|       Atlanta Hawks|         ATL|       Hawks|     Atlanta|      Atlanta|      1949.0|
|1610612738|      Boston Celtics|         BOS|     Celtics|      Boston|Massachusetts|      1946.0|
|1610612739| Cleveland Cavaliers|         CLE|   Cavaliers|   Cleveland|         Ohio|      1970.0|
|1610612740|New Orleans Pelicans|         NOP|    Pelicans| New Orleans|    Louisiana|      2002.0|
|1610612741|       Chicago Bulls|         CHI|       Bulls|     Chicago|     Illinois|      1966.0|
|1610612742|    Dallas Mavericks|         DAL|   Mavericks|      Dallas|        Texas|      1980.0|
|1610612743|      Denver Nuggets|         DEN|     Nuggets|      Denver|     Colorado|      1976.0|
|1610612744|Golden State Warr...|         GSW|    Warriors|Golden State|   California|      1946.0|
|1610612745|     Houston Rockets|         HOU|     Rockets|     Houston|        Texas|      1967.0|
|1610612746|Los Angeles Clippers|         LAC|    Clippers| Los Angeles|   California|      1970.0|
|1610612747|  Los Angeles Lakers|         LAL|      Lakers| Los Angeles|   California|      1948.0|
|1610612748|          Miami Heat|         MIA|        Heat|       Miami|      Florida|      1988.0|
|1610612749|     Milwaukee Bucks|         MIL|       Bucks|   Milwaukee|    Wisconsin|      1968.0|
|1610612750|Minnesota Timberw...|         MIN|Timberwolves|   Minnesota|    Minnesota|      1989.0|
|1610612751|       Brooklyn Nets|         BKN|        Nets|    Brooklyn|     New York|      1976.0|
|1610612752|     New York Knicks|         NYK|      Knicks|    New York|     New York|      1946.0|
|1610612753|       Orlando Magic|         ORL|       Magic|     Orlando|      Florida|      1989.0|
|1610612754|      Indiana Pacers|         IND|      Pacers|     Indiana|      Indiana|      1976.0|
|1610612755|  Philadelphia 76ers|         PHI|       76ers|Philadelphia| Pennsylvania|      1949.0|
|1610612756|        Phoenix Suns|         PHX|        Suns|     Phoenix|      Arizona|      1968.0|
+----------+--------------------+------------+------------+------------+-------------+------------+
only showing top 20 rows

In [35]:
result1 = pd.read_sql_query("SELECT * FROM common_player_info;", conn)
result2 = pd.read_sql_query("SELECT * FROM game;", conn)

result1

,person_id,first_name,last_name,display_first_last,display_last_comma_first,display_fi_last,player_slug,birthdate,school,country,...,playercode,from_year,to_year,dleague_flag,nba_flag,games_played_flag,draft_year,draft_round,draft_number,greatest_75_flag
0,76005,Tom,Abernethy,Tom Abernethy,"Abernethy, Tom",T. Abernethy,tom-abernethy,1954-05-06 00:00:00,Indiana,USA,...,HISTADD_tom_abernethy,1976.0,1980.0,N,Y,Y,1976,3,43,N
1,76006,Forest,Able,Forest Able,"Able, Forest",F. Able,forest-able,1932-07-27 00:00:00,Western Kentucky,USA,...,HISTADD_frosty_able,1956.0,1956.0,N,Y,Y,1956,None,None,N
2,76007,John,Abramovic,John Abramovic,"Abramovic, John",J. Abramovic,john-abramovic,1919-02-09 00:00:00,Salem,USA,...,HISTADD_brooms_abramovic,1946.0,1947.0,N,Y,Y,Undrafted,Undrafted,Undrafted,N
3,203518,Alex,Abrines,Alex Abrines,"Abrines, Alex",A. Abrines,alex-abrines,1993-08-01 00:00:00,FC Barcelona,Spain,...,alex_abrines,2016.0,2018.0,N,Y,Y,2013,2,32,N
4,1630173,Precious,Achiuwa,Precious Achiuwa,"Achiuwa, Precious",P. Achiuwa,precious-achiuwa,1999-09-19 00:00:00,Memphis,Nigeria,...,precious_achiuwa,2020.0,2022.0,N,Y,Y,2020,1,20,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1275,1627757,Stephen,Zimmerman,Stephen Zimmerman,"Zimmerman, Stephen",S. Zimmerman,stephen-zimmerman,1996-09-09 00:00:00,UNLV,USA,...,stephen_zimmerman,2016.0,2016.0,Y,Y,Y,2016,2,41,N
1276,1627835,Paul,Zipser,Paul Zipser,"Zipser, Paul",P. Zipser,paul-zipser,1994-02-18 00:00:00,Bayern Munich,Germany,...,paul_zipser,2016.0,2017.0,Y,Y,Y,2016,2,48,N
1277,78647,Jim,Zoet,Jim Zoet,"Zoet, Jim",J. Zoet,jim-zoet,1953-12-30 00:00:00,Kent State,USA,...,HISTADD_jim_zoet,1982.0,1982.0,N,Y,Y,Undrafted,Undrafted,Undrafted,N
1278,1627826,Ivica,Zubac,Ivica Zubac,"Zubac, Ivica",I. Zubac,ivica-zubac,1997-03-18 00:00:00,Mega Basket,Croatia,...,ivica_zubac,2016.0,2022.0,Y,Y,Y,2016,2,32,N
1279,78650,Matt,Zunic,Matt Zunic,"Zunic, Matt",M. Zunic,matt-zunic,1919-12-19 00:00:00,George Washington,USA,...,HISTADD_matt_zunic,1948.0,1948.0,N,Y,Y,1947,None,None,N

In [54]:
#selecting column
# df_common_player_info.select(["first_name","last_name" ]).show()
#checking the type column
# df_common_player_info.dtypes
#describing column
# df_team.describe().show()
#adding column

+-------+-----------------+------------------+------------+--------+----------+---------+----------------+
|summary|               id|         full_name|abbreviation|nickname|      city|    state|    year_founded|
+-------+-----------------+------------------+------------+--------+----------+---------+----------------+
|  count|               30|                30|          30|      30|        30|       30|              30|
|   mean|   1.6106127515E9|              null|        null|    null|      null|     null|          1969.7|
| stddev|8.803408430829505|              null|        null|    null|      null|     null|16.6984409761655|
|    min|       1610612737|     Atlanta Hawks|         ATL|   76ers|   Atlanta|  Arizona|          1946.0|
|    max|       1610612766|Washington Wizards|         WAS| Wizards|Washington|Wisconsin|          2002.0|
+-------+-----------------+------------------+------------+--------+----------+---------+----------------+

In [90]:
#adding column
#df_team.withColumn("Total YRS in NBA", 2023 - df_team["year_founded"]).show()
#drop the column
team_dataframe = df_team.drop("nickname")
#renaming the column
team_dataframe.select(["full_name", "city"]).count()

30

In [96]:
df_team.select(["full_name"]).show()

+--------------------+
|           full_name|
+--------------------+
|       Atlanta Hawks|
|      Boston Celtics|
| Cleveland Cavaliers|
|New Orleans Pelicans|
|       Chicago Bulls|
|    Dallas Mavericks|
|      Denver Nuggets|
|Golden State Warr...|
|     Houston Rockets|
|Los Angeles Clippers|
|  Los Angeles Lakers|
|          Miami Heat|
|     Milwaukee Bucks|
|Minnesota Timberw...|
|       Brooklyn Nets|
|     New York Knicks|
|       Orlando Magic|
|      Indiana Pacers|
|  Philadelphia 76ers|
|        Phoenix Suns|
+--------------------+
only showing top 20 rows

In [103]:
#dropping nan column(thres=3 check if at least 2 non-nan values are there, then it will keep it )
# df_team.na.drop(how="all").show()
# df_team.na.fill("filling value").show()

+----------+--------------------+------------+------------+------------+-------------+------------+
|        id|           full_name|abbreviation|    nickname|        city|        state|year_founded|
+----------+--------------------+------------+------------+------------+-------------+------------+
|1610612737|       Atlanta Hawks|         ATL|       Hawks|     Atlanta|      Atlanta|      1949.0|
|1610612738|      Boston Celtics|         BOS|     Celtics|      Boston|Massachusetts|      1946.0|
|1610612739| Cleveland Cavaliers|         CLE|   Cavaliers|   Cleveland|         Ohio|      1970.0|
|1610612740|New Orleans Pelicans|         NOP|    Pelicans| New Orleans|    Louisiana|      2002.0|
|1610612741|       Chicago Bulls|         CHI|       Bulls|     Chicago|     Illinois|      1966.0|
|1610612742|    Dallas Mavericks|         DAL|   Mavericks|      Dallas|        Texas|      1980.0|
|1610612743|      Denver Nuggets|         DEN|     Nuggets|      Denver|     Colorado|      1976.0|
|1610612744|Golden State Warr...|         GSW|    Warriors|Golden State|   California|      1946.0|
|1610612745|     Houston Rockets|         HOU|     Rockets|     Houston|        Texas|      1967.0|
|1610612746|Los Angeles Clippers|         LAC|    Clippers| Los Angeles|   California|      1970.0|
|1610612747|  Los Angeles Lakers|         LAL|      Lakers| Los Angeles|   California|      1948.0|
|1610612748|          Miami Heat|         MIA|        Heat|       Miami|      Florida|      1988.0|
|1610612749|     Milwaukee Bucks|         MIL|       Bucks|   Milwaukee|    Wisconsin|      1968.0|
|1610612750|Minnesota Timberw...|         MIN|Timberwolves|   Minnesota|    Minnesota|      1989.0|
|1610612751|       Brooklyn Nets|         BKN|        Nets|    Brooklyn|     New York|      1976.0|
|1610612752|     New York Knicks|         NYK|      Knicks|    New York|     New York|      1946.0|
|1610612753|       Orlando Magic|         ORL|       Magic|     Orlando|      Florida|      1989.0|
|1610612754|      Indiana Pacers|         IND|      Pacers|     Indiana|      Indiana|      1976.0|
|1610612755|  Philadelphia 76ers|         PHI|       76ers|Philadelphia| Pennsylvania|      1949.0|
|1610612756|        Phoenix Suns|         PHX|        Suns|     Phoenix|      Arizona|      1968.0|
+----------+--------------------+------------+------------+------------+-------------+------------+
only showing top 20 rows

+----------+--------------------+------------+------------+------------+-------------+------------+
|        id|           full_name|abbreviation|    nickname|        city|        state|year_founded|
+----------+--------------------+------------+------------+------------+-------------+------------+
|1610612737|       Atlanta Hawks|         ATL|       Hawks|     Atlanta|      Atlanta|      1949.0|
|1610612738|      Boston Celtics|         BOS|     Celtics|      Boston|Massachusetts|      1946.0|
|1610612739| Cleveland Cavaliers|         CLE|   Cavaliers|   Cleveland|         Ohio|      1970.0|
|1610612740|New Orleans Pelicans|         NOP|    Pelicans| New Orleans|    Louisiana|      2002.0|
|1610612741|       Chicago Bulls|         CHI|       Bulls|     Chicago|     Illinois|      1966.0|
|1610612742|    Dallas Mavericks|         DAL|   Mavericks|      Dallas|        Texas|      1980.0|
|1610612743|      Denver Nuggets|         DEN|     Nuggets|      Denver|     Colorado|      1976.0|
|1610612744|Golden State Warr...|         GSW|    Warriors|Golden State|   California|      1946.0|
|1610612745|     Houston Rockets|         HOU|     Rockets|     Houston|        Texas|      1967.0|
|1610612746|Los Angeles Clippers|         LAC|    Clippers| Los Angeles|   California|      1970.0|
|1610612747|  Los Angeles Lakers|         LAL|      Lakers| Los Angeles|   California|      1948.0|
|1610612748|          Miami Heat|         MIA|        Heat|       Miami|      Florida|      1988.0|
|1610612749|     Milwaukee Bucks|         MIL|       Bucks|   Milwaukee|    Wisconsin|      1968.0|
|1610612750|Minnesota Timberw...|         MIN|Timberwolves|   Minnesota|    Minnesota|      1989.0|
|1610612751|       Brooklyn Nets|         BKN|        Nets|    Brooklyn|     New York|      1976.0|
|1610612752|     New York Knicks|         NYK|      Knicks|    New York|     New York|      1946.0|
|1610612753|       Orlando Magic|         ORL|       Magic|     Orlando|      Florida|      1989.0|
|1610612754|      Indiana Pacers|         IND|      Pacers|     Indiana|      Indiana|      1976.0|
|1610612755|  Philadelphia 76ers|         PHI|       76ers|Philadelphia| Pennsylvania|      1949.0|
|1610612756|        Phoenix Suns|         PHX|        Suns|     Phoenix|      Arizona|      1968.0|
+----------+--------------------+------------+------------+------------+-------------+------------+
only showing top 20 rows

In [126]:
df_team_details.show()

+----------+------------+------------+-----------+------------+--------------------+-------------+--------------------+------------------+----------------+--------------------+--------------------+--------------------+--------------------+
|   team_id|abbreviation|    nickname|yearfounded|        city|               arena|arenacapacity|               owner|    generalmanager|       headcoach|  dleagueaffiliation|            facebook|           instagram|             twitter|
+----------+------------+------------+-----------+------------+--------------------+-------------+--------------------+------------------+----------------+--------------------+--------------------+--------------------+--------------------+
|1610612737|         ATL|       Hawks|     1949.0|     Atlanta|    State Farm Arena|      18729.0|        Tony Ressler|    Travis Schlenk|     Quin Snyder|College Park Skyh...|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612738|         BOS|     Celtics|     1946.0|      Boston|           TD Garden|      18624.0|       Wyc Grousbeck|      Brad Stevens|    Joe Mazzulla|       Maine Celtics|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612739|         CLE|   Cavaliers|     1970.0|   Cleveland|Rocket Mortgage F...|      20562.0|         Dan Gilbert|       Koby Altman|  JB Bickerstaff|    Cleveland Charge|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612740|         NOP|    Pelicans|     2002.0| New Orleans|Smoothie King Center|         null|          Tom Benson|    Trajan Langdon|    Willie Green| Birmingham Squadron|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612741|         CHI|       Bulls|     1966.0|     Chicago|       United Center|      21711.0|     Jerry Reinsdorf|Arturas Karnisovas|   Billy Donovan|    Windy City Bulls|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612742|         DAL|   Mavericks|     1980.0|      Dallas|American Airlines...|      19200.0|          Mark Cuban|     Nico Harrison|      Jason Kidd|       Texas Legends|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612743|         DEN|     Nuggets|     1976.0|      Denver|          Ball Arena|         null|        Stan Kroenke|      Calvin Booth|  Michael Malone|   Grand Rapids Gold|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612744|         GSW|    Warriors|     1946.0|Golden State|        Chase Center|         null|           Joe Lacob|         Bob Myers|      Steve Kerr| Santa Cruz Warriors|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612745|         HOU|     Rockets|     1967.0|     Houston|       Toyota Center|      18104.0|     Tilman Fertitta|      Rafael Stone|   Stephen Silas|Rio Grande Valley...|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612746|         LAC|    Clippers|     1970.0| Los Angeles|    Crypto.com Arena|      19060.0|       Steve Ballmer|    Michael Winger|      Tyronn Lue|Agua Caliente Cli...|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612747|         LAL|      Lakers|     1948.0| Los Angeles|    Crypto.com Arena|      19060.0|Jerry Buss Family...|       Rob Pelinka|      Darvin Ham|    South Bay Lakers|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612748|         MIA|        Heat|     1988.0|       Miami|    Miami-Dade Arena|      19600.0|        Micky Arison|         Pat Riley|  Erik Spoelstra|Sioux Falls Skyforce|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612749|         MIL|       Bucks|     1968.0|   Milwaukee|        Fiserv Forum|      17500.0|Wesley Edens & Ma...|         Jon Horst|Mike Budenholzer|      Wisconsin Herd|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612750|         MIN|Timberwolves|     1989.0|   Minnesota|       Target Center|      19356.0|         Glen Taylor|      Tim Connelly|     Chris Finch|         Iowa Wolves|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612751|         BKN|        Nets|     1976.0|    Brooklyn|     Barclays Center|         null|            Joe Tsai|        Sean Marks|   Jacque Vaughn|    Long Island Nets|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612752|         NYK|      Knicks|     1946.0|    New York|Madison Square Ga...|      19763.0|Cablevision (Jame...|         Leon Rose|   Tom Thibodeau|  Westchester Knicks|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612753|         ORL|       Magic|     1989.0|     Orlando|        Amway Center|          0.0|          Rick DeVos|      John Hammond|   Jamahl Mosley|      Lakeland Magic|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612754|         IND|      Pacers|     1976.0|     Indiana|Gainbridge Fieldh...|      18345.0|          Herb Simon|   Kevin Pritchard|   Rick Carlisle| Fort Wayne Mad Ants|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612755|         PHI|       76ers|     1949.0|Philadelphia|  Wells Fargo Center|         null|       Joshua Harris|       Elton Brand|      Doc Rivers| Delaware Blue Coats|https://www.faceb...|https://instagram...|https://twitter.c...|
|1610612756|         PHX|        Suns|     1968.0|     Phoenix|    Footprint Center|         null|          Mat Ishbia|       James Jones|  Monty Williams|        No Affiliate|https://www.faceb...|https://instagram...|https://twitter.c...|
+----------+------------+------------+-----------+------------+--------------------+-------------+--------------------+------------------+----------------+--------------------+--------------------+--------------------+--------------------+
only showing top 20 rows

In [133]:
# df_team_details.show()
# df_team_details.filter("arenacapacity >=15000").select(["nickname", "arenacapacity"]).show()

df_team_details.filter(~(df_team_details["arenacapacity"]> 20000) & (df_team_details["yearfounded"] > 1965)).select(["nickname", "yearfounded"]).show()

+-------------+-----------+
|     nickname|yearfounded|
+-------------+-----------+
|    Mavericks|     1980.0|
|      Rockets|     1967.0|
|     Clippers|     1970.0|
|         Heat|     1988.0|
|        Bucks|     1968.0|
| Timberwolves|     1989.0|
|        Magic|     1989.0|
|       Pacers|     1976.0|
|Trail Blazers|     1970.0|
|        Spurs|     1976.0|
|    Grizzlies|     1995.0|
|      Hornets|     1988.0|
+-------------+-----------+

In [173]:
#groupby aggregrate

df_team_details.groupBy("nickname").max().show()
# print(df_team_details.collect()[0:5])

+---------+------------+----------------+------------------+
| nickname|max(team_id)|max(yearfounded)|max(arenacapacity)|
+---------+------------+----------------+------------------+
|    Bucks|  1610612749|          1968.0|           17500.0|
|  Hornets|  1610612766|          1988.0|           19026.0|
|    Kings|  1610612758|          1948.0|           17500.0|
|    Bulls|  1610612741|          1966.0|           21711.0|
|Grizzlies|  1610612763|          1995.0|           18119.0|
|  Pistons|  1610612765|          1948.0|              null|
|    Magic|  1610612753|          1989.0|               0.0|
|     Jazz|  1610612762|          1974.0|              null|
| Warriors|  1610612744|          1946.0|              null|
|   Pacers|  1610612754|          1976.0|           18345.0|
|     Nets|  1610612751|          1976.0|              null|
|    Hawks|  1610612737|          1949.0|           18729.0|
| Clippers|  1610612746|          1970.0|           19060.0|
|  Wizards|  1610612764|          1961.0|           20647.0|
|  Nuggets|  1610612743|          1976.0|              null|
|  Raptors|  1610612761|          1995.0|              null|
|    76ers|  1610612755|          1949.0|              null|
|   Knicks|  1610612752|          1946.0|           19763.0|
|Mavericks|  1610612742|          1980.0|           19200.0|
|   Lakers|  1610612747|          1948.0|           19060.0|
+---------+------------+----------------+------------------+
only showing top 20 rows

In [174]:
mask = df_player["first_name"].isnull()
result = df_player[mask]

print(result)

In [5]:
import boto3

s3_client = boto3.client('s3')

bucket_name = 'pep2-yg'
object_key = 'baseball/batting.csv'
response = s3_client.get_object(Bucket=bucket_name, Key=object_key)
content = response['Body'].read().decode('utf-8')
print(content)


# s3_resource = boto3.resource('s3')
# object = s3.Object('pep2-yg','baseball/batting.csv')

#pep2-yg/baseball/batting.csv

NoCredentialsError: Unable to locate credentials

In [6]:
s3_resource = boto3.resource('s3')
s3_resource.Object('pep2-yg', 'baseball/batting.csv')

s3.Object(bucket_name='pep2-yg', key='baseball/batting.csv')

In [2]:
import seaborn as sns

In [ ]:
conn = sqlite3.connect('nba.sqlite')
cursor = conn.cursor()
conn.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
output_folder = "csv"
os.makedirs(output_folder, exist_ok=True)

In [ ]:
conn = sqlite3.connect('nba.sqlite')
cursor = conn.cursor()
conn.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
output_folder = "csv"
os.makedirs(output_folder, exist_ok=True)

In [ ]:
##Print the table names
for table in tables:
    table_name = table[0]
    # Read the table data into a pandas DataFrame
    df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    output_file = os.path.join(output_folder, f"{table_name}.csv")
    # Save DataFrame to CSV
    df.to_csv(output_file, index=False)
conn.close()